improve comments, reuse code where possible

diff --git a/crunchwrap b/crunchwrap
--- a/crunchwrap
+++ b/crunchwrap
@@ -110,12 +110,12 @@ _replace_first() {
 
 _escape_html () {
     # Usage: _esacpe_html "hello & goodbye"
-    local string
-    string=${1//&/&amp;}
+    local string="${1}"
+    string=${string//&/&amp;}
     string=${string//</&lt;}
     string=${string//>/&gt;}
     string=${string//'"'/&quot;}
-    printf '%s' "$string"
+    printf '%s' "${string}"
 }
 
 _strip_handlebars() {
@@ -153,50 +153,44 @@ _strip_character_classes() {
     printf '%s\n' "${string}"
 }
 
-_eval_handlebars() {
+_eval_tags() {
+    # Tags that evaluate to empty strings are treated like any other. As
+    # sometimes an empty string is desired in templates. You may override
+    # this behavior by using '{{!' instead. This way crunchwrap will
+    # return a code > 0
+
     local string="${*}"
     local cw_variable cw_value
 
+    # Replace '{{<d>' with '{{'                             (d for delimiter)
+    # -----------------------------------------------------------------------
+    # We must be clever with how we replace '{{%' with '{{'. If we perform
+    # a global find/replace we run the risk of inadverently modifying other
+    # substrings that contain '{{%' that don't have an accompanying '}}'
+
+    # We're able to make the following assumptions for validate tags:
+    # - There will never be any spaces left of '{{%'
+    # - There will be a space to the right of '{{%'
+
+    # Given this criteria I can safely perform a find/replace on '{{% '. The
+    # space after the delimiter is critical!
+
+
+    # fail_when_empty | escape_html | import_template
+    # -----------------------------------------------------------------------
+    # These variables can essentially equal anything. It's set to 'true' for
+    # easy readability, further down all we're doing is making sure the variable
+    # is set. The actual contents of the variable doesn't matter. See `-v`
+    # in man bash.
+
     if [[ "${string}" =~ $regex_crunchwrap_strict_syntax ]]; then
-        # This can equal essentially anything. It's set to 'true' for easy
-        # readability, further down all we're doing is making sure the variable
-        # is set. The actual contents of the variable doesn't matter. See `-v`
-        # in man bash.
         fail_when_empty=true
-        _debug "var: fail_when_empty='${fail_when_empty}'"
-
-        # Replace '{{!' with '{{'
-
-        # I have to be clever with how i replace '{{!' with '{{'. I must be
-        # careful how I perform a find/replace. As there's a super small
-        # chance '{{!' is printed twice. I can make the following assumptions:
-        # - There will not be any spaces left of '{{%'
-        # - There will be a space to the right of '{{%'
-
-        # Given this information I can perform a find/replace on '{{! '. The
-        # added space is critical!
+        _debug "var: fail_when_empty='${fail_when_empty}' for string: '${string}'"
 
         string=$(_replace_first "${string}" "${cw_pattern_left_strict} " "{{ ")
-    fi
-
-    if [[ "${string}" =~ $regex_crunchwrap_escaped_syntax ]]; then
-        # This can equal essentially anything. It's set to 'true' for easy
-        # readability, further down all we're doing is making sure the variable
-        # is set. The actual contents of the variable doesn't matter. See `-v`
-        # in man bash.
+    elif [[ "${string}" =~ $regex_crunchwrap_escaped_syntax ]]; then
         escape_html=true
-        _debug "var: escape_html='${escape_html}'"
-
-        # Replace '{{%' with '{{'
-
-        # I have to be clever with how i replace '{{%' with '{{'. I must be
-        # careful how I perform a find/replace. As there's a super small
-        # chance '{{!' is printed twice. I can make the following assumptions:
-        # - There will not be any spaces left of '{{%'
-        # - There will be a space to the right of '{{%'
-
-        # Given this information I can perform a find/replace on '{{% '. The
-        # added space is critical!
+        _debug "var: escape_html='${escape_html}' for string: '${string}'"
 
         string=$(_replace_first "${string}" "${cw_pattern_left_escaped} " "{{ ")
     fi
@@ -205,43 +199,38 @@ _eval_handlebars() {
     cw_value=$(eval printf '%s' \"\$"${cw_variable}"\")
 
     if [[ -v fail_when_empty ]] && [[ -z "${cw_value}" ]]; then
-         _log "environment variable: '${cw_variable}' evaluated to an empty string. Dying. Use '{{ <string> }}' instead of '{{! <string>}}' if this behavior is not desired."
-         return 126
+        unset fail_when_empty
+        _log "environment variable: '${cw_variable}' evaluated to an empty string. Dying. Use '{{ <string> }}' instead of '{{! <string>}}' if this behavior is not desired."
+        return 126
     fi
-    unset fail_when_empty
 
     if [[ -v escape_html ]] && [[ -n "${cw_value}" ]]; then
+        unset escape_html
         _debug "Calling func: '_escape_html' with argument: ${cw_value}"
         cw_value=$(_escape_html "${cw_value}")
 
         _debug "var: cw_value='${cw_value}'"
     fi
-    unset escape_html
 
     _debug "var: cw_variable='${cw_variable}'"
     _debug "var: cw_value='${cw_value}'"
 
-    # Check for nested crunchwrap variables
+    # Check for nested crunchwrap tags
     if [[ "${cw_value}" =~ $regex_crunchwrap_syntax ]]; then
-        _debug "Found additional handlebars while evaluating: ${cw_variable}"
-        local cw_value_old="${cw_value}"
-        cw_value=''
-        while IFS='' read -r line; do
-            cw_value+="$(_parse "${line}")"
-        done <<< "${cw_value_old}"
+        _debug "Found nested tags while evaluating: '${cw_variable}'"
+        cw_value=$(printf '%s\n' "${cw_value}" | main)
+        # Don't let the above line intimidate you. All we're doing is re-using
+        # exsiting code. We could accomplish the same thing with something like:
+
+        # cw_value_old="${cw_value}"
+        # cw_value=''
+        # while IFS='' read -r line; do
+        #     cw_value+="$(_parse "${line}")"
+        # done <<< "${cw_value_old}"
     fi
 
-    # cw will more than happily pass in empty strings. Be sure that the
-    # equivalent environment variables are set. Why go through all the
-    # trouble? Sometimes we want an empty string
-
-    # Reconstruct pattern. I'm intentionally not using wildcards here. If
-    # their were multiple handlebar templates in a line we'd run into trouble
-    local pattern="${cw_pattern_left} ${cw_variable} ${cw_pattern_right}"
-    local replace="${cw_value}"
-
-    # Reprint the line/segment with the variable resolved
-    printf '%s\n' "${string/$pattern/$replace}"
+    # Print the string with the resolved tag/variable
+    _replace_all "${string}" "${cw_pattern_left} ${cw_variable} ${cw_pattern_right}" "${cw_value}"
 }
 
 _parse() {
@@ -252,13 +241,13 @@ _parse() {
     line=$(_replace_all "${line}" " " " ${cc_space} ") # spaces
     line=$(_replace_all "${line}" $'\t' " ${cc_tab} ") # tabs
 
-    # Take the line that was piped in and split it into an array
-    # Why? there could be multiple template variables on one line
+    # Take the line that was just read in, and split it into an array
+    # Why? there could be multiple crunchrap tags in one line
     IFS=' ' read -r -a line_arr <<< "${line}"
 
     local line_arr_transformed=()
     local line_fragment_arr=()
-    local found_open_handlebars=0 found_handlebar_contents=0 found_closed_handlebars=0
+    local found_open_tag=0 found_tag_contents=0 found_closed_tag=0
     local line_arr_splice_count=0
 
     for ((i = 0; i < "${#line_arr[@]}"; i++)); do
@@ -301,28 +290,28 @@ _parse() {
                 # We found the left: '{{ <string> }}'
                 #                     ^^
                 line_fragment_arr+=("${line_segment}")
-                found_open_handlebars=1
+                found_open_tag=1
                 ;;
             "${cw_pattern_right}"*)
                 _debug "Found right pattern: '${line_segment}'"
                 # We found the right: '{{ <string> }}'
                 #                                  ^^
                 line_fragment_arr+=("${line_segment}")
-                found_closed_handlebars=1
+                found_closed_tag=1
 
                 # Check for mismatched/lone brackets
-                if [[ $found_open_handlebars -eq 0 && $found_closed_handlebars -eq 1 ]]; then
+                if [[ $found_open_tag -eq 0 && $found_closed_tag -eq 1 ]]; then
                     _debug "Found unmatched handlebars. Ignoring '}}'"
-                    found_closed_handlebars=0
+                    found_closed_tag=0
                 fi
 
                 # Found matching starting/ending handlebars
-                # We just flipped 'found_closed_handlebars' above, so their no point in checking it
-                if [[ $found_open_handlebars -eq 1 && $found_handlebar_contents -eq 1 ]]; then
-                    _debug "Calling func: _eval_handlebars with argument: ${line_fragment_arr[*]}"
+                # We just flipped 'found_closed_tag' above, so their no point in checking it
+                if [[ $found_open_tag -eq 1 && $found_tag_contents -eq 1 ]]; then
+                    _debug "Calling func: _eval_tags with argument: ${line_fragment_arr[*]}"
 
                     local results
-                    results=$(_eval_handlebars "${line_fragment_arr[*]}")
+                    results=$(_eval_tags "${line_fragment_arr[*]}")
                     [[ $? -eq 0 ]] || return
 
                     line_arr_transformed+=("${results}")
@@ -330,21 +319,21 @@ _parse() {
                     # Reset. Just in case their are more crunchwrap variables in
                     # the remainder of array: line_arr
                     line_fragment_arr=() # Everything except the first element
-                    found_open_handlebars=0; found_handlebar_contents=0; found_closed_handlebars=0
+                    found_open_tag=0; found_tag_contents=0; found_closed_tag=0
                 fi
                 ;;
             *)
-                if [[ $found_open_handlebars -eq 0  &&  $found_closed_handlebars -eq 0 ]]; then
+                if [[ $found_open_tag -eq 0  &&  $found_closed_tag -eq 0 ]]; then
                     # We haven't found '{{' or '}}' so let's keep on going
                     line_arr_transformed+=("${line_segment}")
                 elif [[ "${line_segment}" =~ $regex_character_class ]]; then
                     _debug "Ignoring crunchwrap character class: '${line_segment}'"
-                elif [[ $found_open_handlebars -eq 1 && $found_closed_handlebars -eq 0 ]]; then
+                elif [[ $found_open_tag -eq 1 && $found_closed_tag -eq 0 ]]; then
                     _debug "Found middle: '${line_segment}'"
                     # We found the middle: '{{ <string> }}'
                     #                          ^^^^^^^^
                     line_fragment_arr+=("${line_segment}")
-                    found_handlebar_contents=1
+                    found_tag_contents=1
                 fi
                 ;;
         esac
@@ -360,15 +349,19 @@ _parse() {
     done
 }
 
-# By default 'read' trims leading/trailing whitespace. so we must use override IFS
-while IFS='' read -r line; do
-    if [[ ! "${line}" =~ $regex_crunchwrap_syntax ]]; then
-        # Pass the unaltered string through if it doesn't contain: {{ <string> }}
-        _debug "Line doesn't match regex. Passing it through unmodified."
-        printf '%s\n' "${line}"
-        continue
-    fi
+main() {
+    # By default 'read' trims leading/trailing whitespace. so we must use override IFS
+    while IFS='' read -r line; do
+        if [[ ! "${line}" =~ $regex_crunchwrap_syntax ]]; then
+            # Pass the unaltered string through if it doesn't contain: {{ <string> }}
+            _debug "Line doesn't match regex. Passing it through unmodified."
+            printf '%s\n' "${line}"
+            continue
+        fi
 
-    # The 'break' is kinda redudant since errexit is enabled
-    _parse "${line}" || break
-done
+        # The 'break' is kinda redundant since errexit is enabled
+        _parse "${line}" || break
+    done
+}
+
+main
